site_name: Bitrix24 Developer Guide
site_url: https://axbuild.github.io/bitrix24-dev-guide/
site_author: "Axbuild"
site_description: "Comprehensive Bitrix24 API Documentation and Developer Guide. Complete reference for Bitrix24 modules, REST API, and development best practices."

# Repository
repo_name: axbuild/bitrix24-dev-guide
repo_url: https://github.com/axbuild/bitrix24-dev-guide
edit_uri: edit/main/docs/

# SEO and Meta Tags
theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.integrate
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  # SEO optimization
  icon:
    logo: material/book-open-page-variant
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono

# SEO Extensions
markdown_extensions:
  - meta
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3

# Плагины
plugins:
  - search:
      lang: 
        - ru
        - en
      separator: '[\s\-\.]+'
  - social:
      cards_color:
        fill: "#0FF1CE" 
        text: "#FFFFFF"
  - tags:
      tags_file: tags.md
  - redirects:
      redirect_maps:
        'old/path.md': 'new/path.md'

# Дополнительный JavaScript
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Дополнительный CSS
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-tomorrow.min.css
  - stylesheets/extra.css

# Кастомизация
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # Replace with your actual Google Analytics ID
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/axbuild
    - icon: fontawesome/brands/telegram
      link: https://t.me/bitrixdevelopers
  alternate:
    - name: Русский
      link: /
      lang: ru
    - name: English
      link: /en/
      lang: en
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  tags:
    - Bitrix24
    - API
    - REST API
    - CRM
    - Development
    - Integration
    - Modules
    - Documentation

# Структура навигации
nav:
  - Главная: index.md
  - Модули:
    - Main: modules/main/index.md
    - CRM: modules/crm/index.md
    - Tasks: modules/tasks/index.md
    - Iblock: modules/iblock/index.md
    - Form: modules/form/index.md
    - Disk: modules/disk/index.md
    - Pull: modules/pull/index.md
    - Socialnetwork: modules/socialnetwork/index.md
    - Calendar: modules/calendar/index.md
    - Forum: modules/forum/index.md
    - Blog: modules/blog/index.md
    - Sale: modules/sale/index.md
    - Catalog: modules/catalog/index.md
    - Support: modules/support/index.md
    - Voximplant: modules/voximplant/index.md
    - Im: modules/im/index.md
    - Mobile: modules/mobile/index.md
  - О проекте:
    - Contributing: about/contributing.md
    - Changelog: about/changelog.md