site_name: Bitrix24 Developer Guide
site_url: https://axbuild.github.io/bitrix24-dev-guide/
site_author: "Axbuild"
site_description: Comprehensive Bitrix24 API Documentation and Developer Guide

# Репозиторий
repo_name: axbuild/bitrix24-dev-guide
repo_url: https://github.com/axbuild/bitrix24-dev-guide
edit_uri: edit/main/docs/

# Конфигурация темы
theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

# Расширения
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences

# Плагины
plugins:
  - search:
      lang: ru

# Дополнительный JavaScript
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Дополнительный CSS
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-tomorrow.min.css

# Кастомизация
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/axbuild
    - icon: fontawesome/brands/telegram
      link: https://t.me/axbuild

# Структура навигации
nav:
  - Главная: index.md
  - Модули:
    - Main: modules/main/index.md
    - CRM:
      - Overview: modules/crm/index.md
      - Leads: modules/crm/leads.md
      - Deals: modules/crm/deals.md
      - Contacts: modules/crm/contacts.md
      - Companies: modules/crm/companies.md
      - Products: modules/crm/products.md
      - Quotes: modules/crm/quotes.md
      - Invoices: modules/crm/invoices.md
    - Tasks: modules/tasks/index.md
    - Iblock: modules/iblock/index.md
    - Form: modules/form/index.md
    - Disk: modules/disk/index.md
    - Pull: modules/pull/index.md
    - Socialnetwork: modules/socialnetwork/index.md
    - Calendar: modules/calendar/index.md
    - Forum: modules/forum/index.md
    - Blog: modules/blog/index.md
    - Sale: modules/sale/index.md
    - Catalog: modules/catalog/index.md
    - Support: modules/support/index.md
    - Voximplant: modules/voximplant/index.md
    - Im: modules/im/index.md
    - Mobile: modules/mobile/index.md
  - О проекте:
    - Contributing: about/contributing.md
    - Changelog: about/changelog.md